#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
# 
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config normal_border_color		"#1f1e33"
bspc config focused_border_color 	"#b3b2f1"
bspc config window_gap          4
bspc config top_padding 2

bspc config focus_follows_pointer true
bspc config pointer_modifier

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# xprop |awk '/WM_CLASS/{print $4}'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-appfinder state=floating follow=on
bspc rule -a Emacs state=tiled

# Autostart Programs
GTK_THEME=Gruvbox-Dark
xrandr -r 143.99 
setxkbmap -option ctrl:swapcaps_hyper
picom &
wmname LG3D
emacs --daemon &
nitrogen --restore &
gnome-keyring-daemon --start &
xscreensaver &
